apiVersion: v1
kind: ServiceAccount
metadata:
  name: agent
  namespace: {{ include "agent.namespace" . }}
  labels:
    {{- include "agent.labels" . | nindent 4 }}
automountServiceAccountToken: false
