name: Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write
  pages: write

jobs:
  release:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: azure/setup-helm@v4
        with:
          version: v3.20.0

      - name: Helm lint
        run: helm lint . --set agent.name=test

      - name: Install helm-unittest
        run: helm plugin install https://github.com/helm-unittest/helm-unittest.git --version v1.0.3

      - name: Run unit tests
        run: helm unittest .

      - name: Package chart
        run: |
          mkdir -p .cr-release-packages
          helm package . -d .cr-release-packages

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.7.0
        with:
          skip_packaging: true
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
